config/routes.rb
Rails.application.routes.draw do
  devise_for :users

	resources :funerals
	
	root 'funerals#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/funeral.rb
class Funeral < ApplicationRecord
	belongs_to :user

	DURATION = 2.hours

	def self.free_slot?(event)
		Funeral.where(start_time: event.slot).any? \
			? false : true
	end

	def slot
		(start_time - DURATION)..(start_time + DURATION)
	end
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :funerals
end

app/models/weather.rb
class Weather < ApplicationRecord

	serialize :data

	def self.ping_weather_api
		return if Weather.find_by_day(Date.today)

		options = {
			units: "metric",
			APPID: "c83b7761430de0c44985771b81874665", # move into ENV
		}
		json = OpenWeather::Forecast.city("Ljubljana, SI", options)

		json["list"].each do |el|
			day = DateTime.strptime(el["dt"].to_s,'%s')
			Weather.where(day: day).first_or_create({data: el})
		end
	end

	def self.ranged(range = 30)
		Weather.where("day >= ?", (Date.today - range.days)).limit(100)
	end

	def temp
		data["main"]["temp"] rescue nil
	end

	def description
		data["weather"][0]["description"] rescue nil
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

	before_action :authenticate_user!
end

app/controllers/funerals_controller.rb
class FuneralsController < ApplicationController

	before_action :find_funeral, only: [:show, :edit, :update, :delete]

	def index
		@funerals = current_user.funerals
		@funeral = Funeral.new
		@weather = Weather.ranged
	end

	def show
		@weather = Weather.where(day: Date.today)
	end

	def new
		@funeral = Funeral.new
		if params[:start_time].present?
			@start_time = DateTime.strptime(params[:start_time], "%Y-%m-%d").at_noon
		end
	end

	def edit
		unless own?
			redirect_to funerals_path
			return
		end
	end

	def create
		funeral = Funeral.new(funeral_params.merge(
			{user_id: current_user.id}))

		if Funeral.free_slot? funeral
			funeral.save!
		else
			flash[:error] = 'This time is already booked!'
		end
		redirect_to funerals_path
	end

	def update
		@funeral.update(funeral_params) if own?
		redirect_to funerals_path
	end

	def delete
		@funeral.destroy if own?
		redirect_to funerals_path
	end

  private

		def find_funeral
			@funeral = Funeral.find(params[:id])
		end

		def own?
			current_user.funerals.include? @funeral
		end

    def funeral_params
      params.require(:funeral).permit(:start_time, :name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funerals_helper.rb
module FuneralsHelper

	def nice(funeral)
		[funeral.name, funeral.start_time.strftime("%H:%M")].join(" @")
	end

	def daytime(time)
		time.strftime("%A, %B #{time.day.ordinalize} @%H:%M")
	end

	def weather_icon(weather, date)
		if day = weather.detect{|w| w.day == date}
			icon = day.data["weather"][0]["icon"] rescue nil
			return "http://openweathermap.org/img/w/#{icon}.png" if icon
		end
	end
end

app/views/funerals/_form.html.erb
<%= form_for @funeral do |f| %>
	<p>Name:<br>
	<%= f.text_field :name, placeholder: 'Name' %></p>
	<p>Start time:<br>
	<%= f.datetime_select :start_time, default: @start_time, minute_step: 15 %></p>
	<%= f.submit %>
<% end %>

app/views/funerals/edit.html.erb
<h3>Edit funeral</h3>

<%= render 'form' %>

app/views/funerals/index.html.erb
<div class="row">
	<div class="col-quarter" style="padding-right:1em">
		<h3>New funeral</h3>
		<%= render 'form' %>

		<% if flash[:error].present? %>
			<p><span style="color:#c00"><%= flash[:error] %></span></p>
		<% end %>
		<br><br>
	</div>
	<div class="col">
		<h3>Funerals</h3>

		<%= month_calendar events: @funerals do |date, funerals| %>
			<img src="<%= weather_icon(@weather, date) %>" style="float:right">
			<%= date.day %>

			<% funerals.each do |funeral| %>
				<div>
					<%= link_to nice(funeral), funeral %>
				</div>
			<% end %>

			<% if date >= Date.today %>
				<br>
				<%= link_to '+', new_funeral_path(start_time: date) %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/funerals/new.html.erb
<h3>New funeral</h3>

<%= render 'form' %>

app/views/funerals/show.html.erb
<h3><%= @funeral.name %></h3>
<h4><%= daytime @funeral.start_time %></h4>

<% if @weather.present? %>
	<img src="<%= weather_icon(@weather, Date.today) %>">
	<br>
	<%= @weather.first.temp %> &deg;C - <%= @weather.first.description %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemodayApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<% if user_signed_in? %>
			<header>
				<ul>
					<li><%= link_to "Funerals", funerals_path %></li>
					<li><%= link_to "New funeral", new_funeral_path %></li>
					<li style='float:right'><%= link_to "Log out &raquo;".html_safe, destroy_user_session_path, :method => :delete %></li>
				</ul>
			</header>
		<% end %>

		<article>
			<%= yield %>
		</article>
  </body>
</html>